#ifndef OEP_EMERGENCE_METRICS_H
#define OEP_EMERGENCE_METRICS_H
#include "oep_core.h"

/* ==============================================================
 * Emergence Quantification Metrics
 * Based on: Crutchfield (1994), Bar-Yam (2004), Prokopenko et al. (2009)
 *
 * Emergence is the appearance of macroscopic order that cannot be
 * trivially reduced to the sum of microscopic parts. Quantifying
 * emergence requires measuring the deviation from "additive" or
 * "reductionist" expectations.
 *
 * Key metrics:
 *   1. Excess entropy / predictive information
 *   2. Integrated information Φ (Tononi, 2004)
 *   3. Causal emergence (Hoel et al., 2013)
 *   4. Downward causation strength
 *   5. Complexity-entropy plane diagnostics
 * ============================================================== */

/* ── Emergence Result ──────────────────────────────────── */

typedef struct {
    double excess_entropy;           /* E = I_pred(macro) - I_pred(micro) */
    double integrated_information;   /* Φ: effective information */
    double causal_emergence;         /* CE = EI_macro - EI_micro */
    double downward_causation;       /* DC strength (macro → micro influence) */
    double mutual_info_macro_micro;  /* I(ξ; x): mutual information */
    double compression_ratio;        /* CR = dim(micro) / dim(macro) */
    double coherence;                /* Phase coherence of collective mode */
    double novelty;                  /* Unpredictability from microscopic rules alone */
    bool   is_genuinely_emergent;    /* True if CE > threshold */
} OEPEmergenceResult;

/* ── Information-Theoretic Metrics ─────────────────────── */

/* Shannon entropy of a discrete probability distribution */
double          oep_em_entropy(const double* prob, int n_states);

/* Joint entropy H(X, Y) */
double          oep_em_joint_entropy(const OEPMatrix* joint_prob,
                                      int n_states_x, int n_states_y);

/* Mutual information I(X; Y) = H(X) + H(Y) - H(X, Y) */
double          oep_em_mutual_information(const OEPMatrix* joint_prob,
                                           int n_states_x, int n_states_y);

/* Conditional entropy H(X|Y) */
double          oep_em_conditional_entropy(const OEPMatrix* joint_prob,
                                            int n_states_x, int n_states_y);

/* Transfer entropy: TE_{Y→X} = I(X_{t+1}; Y_t | X_t)
 * Measures directed information flow from Y to X. */
double          oep_em_transfer_entropy(const double* x, const double* y,
                                         int n, int delay, int n_bins);

/* ── Excess Entropy / Predictive Information ───────────── */

/* Predictive information: I_pred(X) = I(X_past; X_future)
 *   = H(X_future) - H(X_future | X_past)
 * High I_pred indicates structured, predictable dynamics. */
double          oep_em_predictive_information(const double* data, int n,
                                               int past_len, int future_len);

/* Excess entropy: E = lim_{L→∞} [H(L) - L·h_μ]
 *   where H(L) is block entropy, h_μ is entropy rate.
 * Measures the "stored" information in the process. */
double          oep_em_excess_entropy(const double* data, int n,
                                       int max_block_len, double entropy_rate);

/* Compute the complexity-entropy pair (entropy rate, excess entropy)
 * for plotting on the Crutchfield-Young complexity-entropy diagram. */
void            oep_em_complexity_entropy_pair(const double* data, int n,
                                                double* entropy_rate,
                                                double* excess_entropy);

/* ── Integrated Information Φ ──────────────────────────── */

/* Integrated information (Tononi 2004):
 *   Φ = effective information of the whole minus sum of parts.
 * For a bipartition, Φ measures the information generated by the
 * whole that exceeds the independent generation by the parts. */

/* Effective information from a transition probability matrix.
 *   EI = I(X_t; X_{t+1}) under uniform input distribution. */
double          oep_em_effective_information(const OEPMatrix* transition_matrix,
                                              int n_states);

/* Integrated information Φ for bipartition into part1 (size n1) and
 * part2 (size n2). n_states = n1 * n2. */
double          oep_em_integrated_information_bipartition(
                    const OEPMatrix* full_transition,
                    int n1_states, int n2_states);

/* Minimum information bipartition (MIB): find the cut that minimizes Φ. */
double          oep_em_min_information_bipartition(
                    const OEPMatrix* full_transition,
                    int n_vars, int states_per_var);

/* ── Causal Emergence ──────────────────────────────────── */

/* Causal emergence (Hoel et al., 2013):
 *   CE = EI_macro - EI_micro
 * where macro is a coarse-grained description. If CE > 0, the
 * macro-scale has MORE causal power than the micro-scale. */

/* Coarse-grain a micro transition matrix using a mapping f: micro→macro. */
OEPMatrix*      oep_em_coarse_grain_transition(const OEPMatrix* micro_trans,
                                                int n_micro_states,
                                                const int* coarse_mapping,
                                                int n_macro_states);

/* Compute causal emergence for a given coarse-graining. */
double          oep_em_causal_emergence(const OEPMatrix* micro_trans,
                                         int n_micro_states,
                                         const int* coarse_mapping,
                                         int n_macro_states);

/* Find the optimal coarse-graining that maximizes CE. */
double          oep_em_optimal_causal_emergence(const OEPMatrix* micro_trans,
                                                 int n_micro_states,
                                                 int max_macro_states,
                                                 int* best_mapping);

/* ── Downward Causation ────────────────────────────────── */

/* Downward causation DC measures how much the macro state constrains
 * micro dynamics, beyond what the micro alone predicts.
 *   DC = H(micro_{t+1} | micro_t) - H(micro_{t+1} | micro_t, macro_t) */
double          oep_em_downward_causation(const OEPMatrix* micro_data,
                                           const OEPVector* macro_state,
                                           int n_obs, int n_micro_vars,
                                           int n_macro_states, int n_bins);

/* ── Holistic Emergence Metrics ────────────────────────── */

/* Multi-scale complexity: the sum of excess entropies across all scales. */
double          oep_em_multiscale_complexity(const double* data, int n,
                                              int n_scales);

/* Compute full emergence profile for a system. */
OEPEmergenceResult* oep_em_analyze_emergence(const OEPMatrix* micro_data,
                                              const OEPVector* macro_data,
                                              int n_obs, int n_micro_vars,
                                              int n_bins_micro, int n_bins_macro);
void                oep_em_result_free(OEPEmergenceResult* result);

/* Threshold test for genuine emergence. */
bool            oep_em_is_genuine_emergence(const OEPEmergenceResult* r,
                                              double ce_threshold,
                                              double phi_threshold);

/* Print emergence analysis results. */
void            oep_em_result_print(const OEPEmergenceResult* r);

#endif
